### ISSUE TITLE
help, i'm new to java and I don't know what this means...

### ISSUE THREAD

**Issue by sunguytogood** [xXNurioXx/minecraft-server-pinger#9]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
        at me.nurio.minecraft.pinger.MinecraftServerPinger.ping(MinecraftServerPinger.java:24)
        at Sticky.main(Sticky.java:19)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by nuriofernandez** [comment]
You need to add Jackson dependency to your project.
